[app]
name = "counter"
version = "0.1.0"
organization = "com.flui.demo"

[build]
target_platforms = ["windows", "linux", "macos"]

[assets]
# Asset directories
directories = ["assets"]

[fonts]
# Custom fonts can be added here
# [[fonts]]
# family = "Roboto"
# fonts = [
#     { asset = "fonts/Roboto-Regular.ttf", weight = 400, style = "normal" },
# ]
